[pytest]
testpaths =
    tests
markers =
    unit_test: marks tests as unit tests (deselect with '-m "not unit_test"')
    integration_test: marks tests as integration tests (deselect with '-m "not integration_test"')