name: CD Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cd-deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    environment: test
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: 07ec66d2-eff9-4580-91c1-1fdef498c3e7
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12.3'

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py bdist_wheel
          pip install ./dist/rs_project-0.0.10-py3-none-any.whl
          pip install -r requirements-pyspark.txt

      - name: Validate asset bundle for test
        working-directory: .
        run: databricks bundle Validate
             --target test

      - run: databricks bundle deploy --target test
        working-directory: .

  cd-deploy-prod:
    name: Deploy to PROD
    needs: cd-deploy-test
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12.3'

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          python setup.py bdist_wheel
          pip install ./dist/rs_project-0.0.10-py3-none-any.whl
          pip install -r requirements-pyspark.txt

      - name: Configure Databricks
        run: |
          # write out the profile (here called "PROD")
          cat <<EOF > ~/.databrickscfg
          [PROD]
          host = ${{ vars.DATABRICKS_HOST }}
          EOF

      - name: Validate asset bundle for prod
        working-directory: .
        run: databricks bundle Validate
             --target prod --profile PROD
             --var="service_principal_id_prod=${{ secrets.DATABRICKS_CLIENT_ID }}"
          
      - run: databricks bundle deploy --target prod --profile PROD
        working-directory: .
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
