name: CD Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  cd-deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    environment: test
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12.3'

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Dependencies
        run: |
          uv build
          uv sync --only-group integration-tests
          uv pip install -e .

      - name: Configure Databricks
        run: |
          # write out the profile (here called "TEST")
          cat <<EOF > ~/.databrickscfg
          [TEST]
          host = ${{ vars.DATABRICKS_HOST }}
          client_id = ${{ secrets.DATABRICKS_CLIENT_ID }}
          EOF

      - name: Validate asset bundle for test
        working-directory: .
        run: databricks bundle Validate
             --target test
             --profile TEST
             --var="service_principal_id=${{ secrets.DATABRICKS_CLIENT_ID }}"

      - name: Deploy to TEST
        working-directory: .
        run: databricks bundle deploy
             --target test
             --profile TEST
             --var="service_principal_id=${{ secrets.DATABRICKS_CLIENT_ID }}"
      
      - name: Run pytest
        run: |
          uv run pytest -m integration_test \
            --cov-report=html

      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

  cd-deploy-prod:
    name: Deploy to PROD
    needs: cd-deploy-test
    runs-on: ubuntu-latest
    environment: prod
    env:
      DATABRICKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_CLIENT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.2

      - name: Setup Python
        uses: actions/setup-python@v6.2.0
        with:
          python-version: '3.12.3'

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Install Dependencies
        run: |
          uv build
          uv sync --only-group integration-tests
          uv pip install -e .

      - name: Configure Databricks
        run: |
          # write out the profile (here called "PROD")
          cat <<EOF > ~/.databrickscfg
          [PROD]
          host = ${{ vars.DATABRICKS_HOST }}
          client_id = ${{ secrets.DATABRICKS_CLIENT_ID }}
          EOF

      - name: Validate asset bundle for prod
        working-directory: .
        run: databricks bundle Validate
             --target prod
             --profile PROD
             --var="service_principal_id=${{ secrets.DATABRICKS_CLIENT_ID }}"

      - name: Deploy to PROD
        working-directory: .
        run: databricks bundle deploy
             --target prod
             --profile PROD
             --var="service_principal_id=${{ secrets.DATABRICKS_CLIENT_ID }}"